= Immediate Lessons and Next Steps

== Immediate Lessons

* There were areas where more documentation was needed to help with coding the API.
* Code sprints can be good ways to get new developers into implementing a standard.
* The v0.0.6 API definition document was evolving, so the previous version offered an stable alternative.
* It was helpful having participants from different SWGs participate in the same code sprint. It's helpful to have multiple specifications covered by the same code sprint.
* The fact that we had multiple programming languages and client-side/server-side apps, showed diversity of support and will benefit the evolution of the standard.
* An extended agenda that enables participation from more timezones should be applied and promoted in future code sprints.
* Consider a rolling agenda for supporting more timezones.
* The Networking had some participation. Should be considered in the future and possibly evolved.
* More clarification of the role of the different communication channels (e.g. Gitter, GitHub issues) would be useful. Add to the FAQ.


== Next Steps for the Innovation Program

* A follow-on code sprint to help advance the OGC API - DGGS candidate standard.
* Prototyping of CQL support in OGC API - DGGS.
* Reinvigorate work around the DGGS Registry, including support for the latest version of the DGGS Abstract Spec.
* Prototyping of spatio-temporal DGGS and trajectories (e.g. integration of EDR and DGGS building blocks).
* Prototyping of an encoding of DGGS RS parameters (like a WKT DGGS RS, possibly consistent with a JSON Schema representation).
* Experimentation with very large datasets, and exploration of Big Data use cases.
* Share experiences on support for very large datasets, including reusability.
* Experimentation of applying DGGS to other planets (relevant to the Planetary DWG). Some of the questions that could come up include would the equal area characteristic hold on those planets? ...
* Visualization of height maps or extruded 3D cells from a DGGS
* Experimentation of the use of DGGS in Machine Learning applications.


== Next Steps for the Standards Program

* Modularisation of the OGC API - DGGS into building blocks.
* Explore whether there is a need for a conformance class for a 3D portrayal format such as KML, IFC, or other.
* Consider specification of a conformance class or guidance for hierachical collections in OGC API - Common. Probably for future versions or future extensions.
* Consider functional grouping of conformance classes relating to query operations. 
* Consider how versioning is applied at conformance class, building block, and other levels - particularly when combining different versions of the same API in the same solution.
* A roadmap of when the various OGC API standards that have been approved and those that are in development are going to be updated to support OGC API - Common (assuming that OGC API - Common is approved as a standard).
* TBA
